# Generated by Django 3.1.8 on 2022-06-23 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichner', models.CharField(max_length=30)),
                ('strasse', models.CharField(max_length=30)),
                ('hausnummer', models.CharField(max_length=8)),
                ('plz', models.CharField(max_length=5)),
                ('stadt', models.CharField(max_length=30)),
                ('is_home', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('vorname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('kuerzel', models.CharField(max_length=30)),
                ('einsatzbuero', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assistent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('vorname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('einstellungsdatum', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('vorname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('einstellungsdatum', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lohn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erfahrungsstufe', models.IntegerField()),
                ('gueltig_ab', models.DateTimeField()),
                ('eingruppierung', models.IntegerField()),
                ('grundlohn', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kurzfristig_zuschlag_prozent', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('nacht_zuschlag', models.DecimalField(decimal_places=2, max_digits=5)),
                ('samstag_zuschlag', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sonntag_zuschlag', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feiertag_zuschlag', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wechselschicht_zuschlag', models.DecimalField(decimal_places=2, max_digits=5)),
                ('orga_zuschlag', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ueberstunden_zuschlag', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hl_abend_zuschlag', models.DecimalField(decimal_places=2, max_digits=5)),
                ('silvester_zuschlag', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PFK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('vorname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('einstellungsdatum', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entfernung', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dauer_in_minuten', models.IntegerField()),
                ('adresse1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assistenten.adresse')),
                ('adresse2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assistenten.adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Urlaub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginn', models.DateTimeField()),
                ('ende', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('assistent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistenten.assistent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchichtTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginn', models.TimeField()),
                ('ende', models.TimeField()),
                ('bezeichner', models.CharField(max_length=30)),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistenten.asn')),
            ],
        ),
        migrations.CreateModel(
            name='Schicht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginn', models.DateTimeField()),
                ('ende', models.DateTimeField()),
                ('ist_kurzfristig', models.BooleanField(default=0)),
                ('ist_ausfallgeld', models.BooleanField(default=0)),
                ('ist_assistententreffen', models.BooleanField(default=0)),
                ('ist_pcg', models.BooleanField(default=0)),
                ('ist_schulung', models.BooleanField(default=0)),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistenten.asn')),
                ('assistent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistenten.assistent')),
                ('beginn_adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assistenten.adresse')),
                ('ende_adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assistenten.adresse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FesteSchicht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wochentag', models.CharField(max_length=10)),
                ('beginn', models.TimeField()),
                ('ende', models.TimeField()),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistenten.asn')),
                ('assistent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistenten.assistent')),
            ],
        ),
        migrations.CreateModel(
            name='Brutto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monat', models.DateTimeField()),
                ('bruttolohn', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stunden_gesamt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assistent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistenten.assistent')),
            ],
        ),
        migrations.CreateModel(
            name='AU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginn', models.DateTimeField()),
                ('ende', models.DateTimeField()),
                ('assistent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistenten.assistent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssociationAsAsn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_festes_team', models.BooleanField(default=0)),
                ('is_vertretungsteam', models.BooleanField(default=0)),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistenten.asn')),
                ('assistent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistenten.assistent')),
            ],
        ),
        migrations.AddField(
            model_name='assistent',
            name='asns',
            field=models.ManyToManyField(related_name='assistents', through='assistenten.AssociationAsAsn', to='assistenten.ASN'),
        ),
        migrations.AddField(
            model_name='assistent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asn',
            name='einsatzbegleitung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asns', to='assistenten.eb'),
        ),
        migrations.AddField(
            model_name='asn',
            name='pflegefachkraft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asns', to='assistenten.pfk'),
        ),
        migrations.AddField(
            model_name='asn',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistenznehmer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adresse',
            name='asn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adressen', to='assistenten.asn'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='assistent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adressen', to='assistenten.assistent'),
        ),
    ]
