# Generated by Django 3.1.7 on 2021-03-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brutto',
            name='bruttolohn',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='brutto',
            name='stunden_gesamt',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='lohn',
            name='feiertag_zuschlag',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='lohn',
            name='grundlohn',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='lohn',
            name='hl_abend_zuschlag',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='lohn',
            name='nacht_zuschlag',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='lohn',
            name='orga_zuschlag',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='lohn',
            name='samstag_zuschlag',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='lohn',
            name='silvester_zuschlag',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='lohn',
            name='sonntag_zuschlag',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='lohn',
            name='ueberstunden_zuschlag',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='lohn',
            name='wechselschicht_zuschlag',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='weg',
            name='entfernung',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
