# Generated by Django 3.1.7 on 2021-04-06 10:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0005_auto_20210328_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='asn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adressen', to='assistenten.asn'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='assistent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adressen', to='assistenten.assistent'),
        ),
        migrations.AlterField(
            model_name='assistent',
            name='einstellungsdatum',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
