# Generated by Django 3.1.8 on 2021-04-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0007_auto_20210406_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistent',
            name='asn',
        ),
        migrations.AddField(
            model_name='assistent',
            name='asns',
            field=models.ManyToManyField(related_name='assistents', through='assistenten.AssociationAsAsn', to='assistenten.ASN'),
        ),
    ]
