# Generated by Django 3.1.8 on 2021-04-08 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0008_auto_20210408_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asn',
            name='einsatzbegleitung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asns', to='assistenten.eb'),
        ),
        migrations.AlterField(
            model_name='asn',
            name='pflegefachkraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asns', to='assistenten.pfk'),
        ),
    ]
