# Generated by Django 3.1.8 on 2021-04-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0009_auto_20210408_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festeschicht',
            name='beginn',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='festeschicht',
            name='ende',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schichttemplate',
            name='beginn',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schichttemplate',
            name='ende',
            field=models.TimeField(),
        ),
    ]
