# Generated by Django 3.1.8 on 2021-05-09 22:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0010_auto_20210417_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='asn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adressen', to='assistenten.asn'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='assistent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adressen', to='assistenten.assistent'),
        ),
        migrations.AlterField(
            model_name='assistent',
            name='einstellungsdatum',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
