# Generated by Django 3.1.8 on 2021-05-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0012_auto_20210513_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlaub',
            name='beginn',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='urlaub',
            name='ende',
            field=models.DateField(),
        ),
    ]
