# Generated by Django 3.1.8 on 2021-05-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0013_auto_20210517_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='lohn',
            name='kurzfristig_zuschlag_prozent',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AlterField(
            model_name='au',
            name='beginn',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='au',
            name='ende',
            field=models.DateField(),
        ),
    ]
