# Generated by Django 3.1.8 on 2021-06-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0014_auto_20210517_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weg',
            old_name='adresse1_id',
            new_name='adresse1',
        ),
        migrations.RenameField(
            model_name='weg',
            old_name='adresse2_id',
            new_name='adresse2',
        ),
    ]
