# Generated by Django 3.1.8 on 2021-05-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0014_auto_20210517_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schicht',
            name='ist_assistententreffen',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='schicht',
            name='ist_ausfallgeld',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='schicht',
            name='ist_kurzfristig',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='schicht',
            name='ist_pcg',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='schicht',
            name='ist_schulung',
            field=models.BooleanField(default=0),
        ),
    ]
