# Generated by Django 3.1.8 on 2021-06-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0015_auto_20210607_1205'),
        ('assistenten', '0015_auto_20210518_1627'),
    ]

    operations = [
    ]
