# Generated by Django 3.1.8 on 2021-07-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0016_merge_20210614_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistent',
            options={'permissions': (('edit_this_assistent', 'Assistent bearbeiten'),)},
        ),
    ]
