# Generated by Django 3.1.8 on 2021-07-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0017_auto_20210702_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistent',
            options={},
        ),
    ]
