# Generated by Django 3.1.8 on 2021-07-05 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistenten', '0020_asn_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asn',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistenznehmer', to=settings.AUTH_USER_MODEL),
        ),
    ]
