# Generated by Django 3.1.8 on 2021-07-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0021_auto_20210705_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationasasn',
            name='fest_vertretung',
        ),
        migrations.AddField(
            model_name='associationasasn',
            name='is_festes_team',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='associationasasn',
            name='is_vertretungsteam',
            field=models.BooleanField(default=0),
        ),
    ]
