# Generated by Django 3.1.8 on 2022-06-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0022_auto_20210712_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='au',
            name='beginn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='au',
            name='ende',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='urlaub',
            name='beginn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='urlaub',
            name='ende',
            field=models.DateTimeField(),
        ),
    ]
