# Generated by Django 3.1.8 on 2021-07-27 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0022_auto_20210712_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sperrzeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginn', models.DateTimeField()),
                ('ende', models.DateTimeField()),
                ('asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assistenten.asn')),
                ('assistent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assistenten.assistent')),
            ],
        ),
        migrations.CreateModel(
            name='FesteSperrzeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wochentag', models.IntegerField()),
                ('beginn', models.TimeField()),
                ('ende', models.TimeField()),
                ('asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assistenten.asn')),
                ('assistent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assistenten.assistent')),
            ],
        ),
    ]
