# Generated by Django 3.1.8 on 2022-06-05 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0023_auto_20220604_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='eb',
            name='einstellungsdatum',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pfk',
            name='einstellungsdatum',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
