# Generated by Django 3.1.8 on 2022-06-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0024_auto_20220605_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asn',
            name='email',
        ),
    ]
