# Generated by Django 3.1.8 on 2022-06-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0025_remove_asn_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='asn',
            name='email',
            field=models.CharField(default='@', max_length=30),
            preserve_default=False,
        ),
    ]
