# Generated by Django 3.1.8 on 2022-03-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0025_auto_20220316_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='au',
            name='beginn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='au',
            name='ende',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='urlaub',
            name='beginn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='urlaub',
            name='ende',
            field=models.DateTimeField(),
        ),
    ]
