# Generated by Django 3.1.8 on 2022-06-06 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0026_asn_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlaub',
            name='assistent',
        ),
        migrations.RemoveField(
            model_name='urlaub',
            name='beginn',
        ),
        migrations.RemoveField(
            model_name='urlaub',
            name='ende',
        ),
        migrations.RemoveField(
            model_name='urlaub',
            name='id',
        ),
        migrations.AddField(
            model_name='urlaub',
            name='au_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assistenten.au'),
            preserve_default=False,
        ),
    ]
