# Generated by Django 3.1.8 on 2022-06-09 09:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0028_auto_20220607_1244'),
    ]

    operations = [
    ]
