# Generated by Django 3.1.8 on 2022-06-09 12:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assistenten', '0029_auto_20220609_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlaub',
            name='au_ptr',
        ),
        migrations.AddField(
            model_name='urlaub',
            name='assistent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assistenten.assistent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlaub',
            name='beginn',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlaub',
            name='ende',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
